config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  root to: 'pages#home'
  get 'bio', to: 'pages#bio'
  get 'welcome', to: 'pages#welcome'
  resources :artworks
  resources :phases
  resources :shows
  resources :lives
  resources :writings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  # has_one_attached :photo
  # belongs_to :phase

  # validates :title, presence: true
  # validates :year, presence: true
  # validates :height, presence: true
  # validates :width, presence: true
  # validates :depth, presence: true
  # validates :technique, presence: true
  # validates :about, presence: true
  # validates :description, presence: true
  # validates :period, presence: true
end

app/models/live.rb
class Live < ApplicationRecord
end

app/models/phase.rb
class Phase < ApplicationRecord
  has_many :artworks
end

app/models/show.rb
class Show < ApplicationRecord
end

app/models/writing.rb
class Writing < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artworks

  def index
  end

  def show
    @artwork = Artwork.find(params[:id])
  end

  private

  def set_artworks
    @artworks = Artwork.all
  end
end

app/controllers/lives_controller.rb
class LivesController < ApplicationController
  before_action :set_lives

  def index
  end

  def show
    @live = Live.find(params[:id])
  end

  private

  def set_lives
    @lives = Live.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  private

  def set_artworks
    @artworks = Artwork.all
  end
end

app/controllers/phases_controller.rb
class PhasesController < ApplicationController
  before_action :set_phases

  def index
  end

  def show
    @phase = Phase.find(params[:id])
  end

  private

  def set_phases
    @phases = Phase.all
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_shows

  def index
  end

  def show
    @show = Show.find(params[:id])
  end

  private

  def set_shows
    @shows = Show.all
  end
end

app/controllers/writings_controller.rb
class WritingsController < ApplicationController
  before_action :set_writings

  def index
  end

  def show
  end

  private

  def set_writings
    @writings = Writing.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artworks/index.html.erb
<div class="left flex-grow">
  <div class="bg-gray-100 h-screen px-12 py-12">
    <% @artworks.each do |artwork| %>
      <h1 class="text-4xl hover:text-yellow-500 uppercase animate__animated animate__fadeInDown"><%= link_to artwork.title, artwork_path(artwork) %></h1>
    <% end %>
  </div>
</div>

app/views/artworks/show.html.erb
<!-- <div class="left">
  <div class="h-screen px-4 pt-5">
    <% @artworks.each do |artwork| %>
      <h1 class="text-4xl hover:text-yellow-500"><%= link_to artwork.title %></h1>
    <% end %>
  </div>
</div> -->

<div class="flex">

  <div class="right w-1/2 ">
    <div style="height: 1800px;">
      <div>
        <%= image_tag asset_path('nascimiento.jpg') %>
      </div>
      <div class="">
        <%= image_tag asset_path('dorso.jpg') %>
      </div>

    </div>
  </div>

  <div class="left w-1/2 ">
    <div style="height: 1800px;">
      <div>
        <%= image_tag asset_path('nun2.png') %>
      </div>
      <div class="">
        <%= image_tag asset_path('sos.jpg') %>
      </div>
      <div>
        <%= image_tag asset_path('grande.jpg') %>
      </div>
    </div>
  </div>

  <div class="right w-1/2">
    <div style="height: 1800px;">
      <div>
        <%= image_tag asset_path('fiesta.jpg') %>
      </div>

    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>albertogreco.com</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('icono.png') %>

  </head>

  <body class="font-mono">
    <div class="text-gray-600 flex">

      <% unless content_for? :menu %>


        <div class=" px-4 w-14 flex-none">
          <div style="position: fixed;">
            <ul class="menu py-12">
              <div class="">
                <li class="menu_i hover:text-yellow-500"><span class="menu_i_tx"><%= link_to "BIOGRAFIA", bio_path %></span></li>
                <li class="menu_i hover:text-yellow-500"><span class="menu_i_tx"><%= link_to "OBRAS", phases_path %></span></li>
                <li class="menu_i hover:text-yellow-500"><span class="menu_i_tx"><%= link_to "ARTE VIVO", lives_path %></span></li>
                <!-- <li class="menu_i hover:text-yellow-500"><span class="menu_i_tx"><%= link_to "ETAPAS", phases_path %></span></li> -->
                <li class="menu_i hover:text-yellow-500"><span class="menu_i_tx"><%= link_to "MUESTRAS", shows_path %></span></li>
<!--                 <li class="menu_i hover:text-yellow-500"><span class="menu_i_tx"><%= link_to "PUBLICACIONES", writings_path %></span></li>
                <li class="menu_i hover:text-yellow-500"><span class="menu_i_tx"><%= link_to "PRENSA", shows_path %></span></li> -->
                <li class="menu_i hover:text-yellow-500"><span class="menu_i_tx"><%= link_to "✕", root_path %></span></li>
              </div>
              <div class="menu_i"> <%= link_to(image_tag("icono.png"), welcome_path) %></div>

            </ul>


          </div>
        </div>

       <% end %>


      <%= yield %>

    </div>
  </body>
</html>

app/views/lives/index.html.erb
<div class="menu justify-center x-4 w-14 flex-none">
  <div class="bg-gray-300 h-screen px-4 pt-12">
    <% @lives.each do |live| %>
      <div class="menu_i hover:text-white pt-3 pb-2 uppercase animate__animated animate__fadeInDown"><%= link_to live.abbreviation, life_path(live), class:"menu_i_tx over:text-white" %></div>
    <% end %>
    <!-- <div class="menu_i hover:text-yellow-500"><span class="menu_i_tx"><%= link_to "✕", phases_path %></span></div> -->
  </div>
</div>


<div class="pt-12 pl-12">
  <h1 class="pb-6 text-yellow-500 text-4xl animate__animated animate__fadeInDown">ARTE VIVO</h1>

  <div>
    <% @lives.each do |live| %>
    <div class="py-2">
      <h1><%= live.title %></h1>
      <h1><%= live.about %></h1>
      <h1> <%= live.details %></h1>
    </div>
    <% end %>
  </div>

</div>


<!-- <div class="left flex-grow">
  <div class="bg-gray-100 h-screen px-12 py-12">
    <% @lives.each do |live| %>
      <h1 class="text-4xl hover:text-yellow-500 uppercase animate__animated animate__fadeInDown"><%= link_to live.title, life_path(live) %></h1>
    <% end %>
  </div>
</div>
 -->

app/views/lives/show.html.erb
<div class="menu justify-center x-4">
  <div class="bg-yellow-100 h-screen px-4 flex-none">
    <% @lives.each do |live| %>
      <div class="menu_i hover:text-yellow-500 pt-3 pb-2"><%= link_to live.abbreviation, life_path(live), class:"menu_i_tx hover:text-yellow-500" %></div>
    <% end %>
    <div class="menu_i hover:text-yellow-500"><span class="menu_i_tx"><%= link_to "✕", lives_path %></span></div>
  </div>
</div>


<%= @live.title %>

app/views/pages/bio.html.erb
<div class="encapsulate bg-gray-100 pb-12">

  <div class="animate__animated animate__fadeInUp">
    <h2 class="timelineTitle"> Alberto Greco</h2>
    <h4>
    Nace en Buenos Aires, Argentina en 1931 y es reconocido como uno de los pioneros de la vanguardia informalista argentina al integrar en 1959 el Movimiento Informalista Argentino.
    En 1961 realiza su última muestra de pinturas en Buenos Aires en la galería Pizarro, en la cual presenta la serie Las Mojas.
    Poco después se instala en Paris donde realiza, en 1962, la Primera Exposición de Arte Vivo, “firmando” personas.
    En 1963 viaja a Piedralaves en Ávila, España, donde realiza la serie de acciones fotografiadas por Montserrat Santamaría.
    En Génova, en ese mismo año, publica el Manifiesto Dito dell’Arte Vivo en italiano.
    En 1964, expone en la galería Juana Mordó en Madrid y regresa a Buenos Aires, donde presenta su experiencia de Arte Vivo: Mi Madrid querido. Pintura espectáculo Vivo-Dito, con colaboración del bailarín Antonio Gades.
    En 1965, se instala en Barcelona, ciudad en la cual se quita la vida.
    </h4>

    <div class="flex my-6 justify-center space-between">
      <div>
        <%= image_tag asset_path('alberto1.jpg') %>
      </div>
      <div>
        <%= image_tag asset_path('nun2.png') %>
      </div>
            <div>
        <%= image_tag asset_path('alberto.jpg') %>
      </div>
    </div>

    <h2 class="timelineTitle">Trayectoria</h2>

    <div class="timeline">
      <div>
        <h3 class="year">1947</h3>
        <h3 class="year">1948</h3>
      </div>
      <h4>Asiste a los talleres de Cecilia Marcovich y Tomas Maldonado.</h4>
    </div>

    <div class="timeline">
      <h3 class="year">1954</h3>
      <h4>Beca del Gobierno Francés para mudarse a París.</h4>
    </div>

    <div class="timeline">
      <h3 class="year">1955</h3>
      <h4>Expone en la galería La Roue – <i>París, Francia</i></h4>
    </div>

    <div class="timeline">
      <h3 class="year">1956</h3>
      <h4>Regresa a Buenos Aires y expone en la galería Antígona. Expone en la galería Petit Galerie – <i>Río de Janeiro, Brasil</i></h4>
    </div>

    <div class="timeline">
      <h3 class="year">1958</h3>
      <h4>Expone en Museo de Arte Moderno – <i>Sao Paulo, Brasil</i></h4>
    </div>

    <div class="timeline">
      <h3 class="year">1958</h3>
      <h4>Premio Adquisición del Estado de San Pablo en pintura.</h4>
    </div>

    <div class="timeline">
      <h3 class="year">1959</h3>
      <h4>Integra Movimiento Informalista con Kenneth Kemble, López, Maza, Martha Pucciarelli, y Luis Wells, entre otros.</h4>
    </div>

    <div class="timeline">
      <h3 class="year">1959</h3>
      <div>
        <h4>Movimiento Informalista. Galería Van Riel – <i>Buenos Aires, Argentina </i></h4>
        <h4>Informalismo. Galería Pizarro – <i>Buenos Aires, Argentina</i></h4>
      </div>
    </div>

    <div class="timeline">
      <h3 class="year">1960</h3>
      <h4>Expone en Galería Pizarro – <i>Buenos Aires, Argentina</i> Participa en VI Salón Anual de Arte Nuevo. Museo Eduardo Sívori – <i>Buenos Aires, Argentina</i></h4>
    </div>

    <div class="timeline">
      <h3 class="year">1960</h3>
      <h4>Premio de Ridder.</h4>
    </div>

    <div class="timeline">
      <h3 class="year">1961</h3>
      <h4>Las Monjas. Galería Pizarro – <i>Buenos Aires, Argentina</i></h4>
    </div>

    <div class="timeline">
      <h3 class="year">1962</h3>
      <h4>Pablo (Curatella) Manes y 30 artistas argentinos de Nueva Generación. Galería Creuze Messine – <i>París, Francia</i></h4>
    </div>

    <div class="timeline">
      <h3 class="year">1964</h3>
      <h4>Expone en Galería Juana Mordó – <i>Madrid, España</i></h4>
    </div>


    <h2 class="timelineTitle">Exhibiciones póstumas</h2>

    <div class="timeline">
      <h3 class="year">1965</h3>
      <h4>Homenaje a Alberto Greco. Galería Pizarro – <i>Buenos Aires, Argentina</i></h4>
    </div>

    <div class="timeline">
      <h3 class="year">1967</h3>
      <h4>Salón de Jeune Peinture – <i>París, Francia</i></h4>
    </div>

    <div class="timeline">
      <h3 class="year">1987</h3>
      <h4>Alberto Greco a cinco anos de su muerte. Galería Carmen Waugh – <i>Buenos Aires, Argentina</i></h4>
    </div>

    <div class="timeline">
      <h3 class="year">1988</h3>
      <h4>Alberto Greco y Rubén Santatonín. Fundación San Telmo – <i>Buenos Aires, Argentina</i></h4>
    </div>

    <div class="timeline">
      <h3 class="year">1991</h3>
      <h4>Alberto Greco. IVAM Centro Julio González – <i>Valencia, España</i></h4>
    </div>

    <div class="timeline">
      <h3 class="year">1992</h3>
      <h4>Alberto Greco. Museo Nacional de Bellas Arte – <i>Buenos Aires, Argentina</i></h4>
    </div>

    <div class="timeline">
      <h3 class="year">1996</h3>
      <h4>Alberto Greco. Obras extraviadas. Centro Cultural Borges – <i>Buenos Aires, Argentina</i></h4>
    </div>


    <h2 class="timelineTitle">Colecciones públicas</h2>
    <h3 class="py-2">Museo de Arte Contemporáneo de Rosario – <i>Rosario, Argentina</i></h3>
    <h3 class="py-2">Museo de Arte Moderno de Buenos Aires – <i>Buenos Aires, Argentina</i></h3>
    <h3 class="py-2">Museo Nacional de Bellas Arte – <i>Buenos Aires, Argentina</i></h3>
    <h3 class="py-2">Museum of Modern Art - <i>Nueva York, Estados Unidos</i></h3>
    <h3 class="py-2">Fundación Federico Jorge Klemm – <i>Buenos Aires, Argentina</i></h3>
    <h3 class="py-2">Museo Nacional Centro de Arte Reina Sofía – <i>Madrid, España</i></h3>
  </div>
</div>


<!-- <div class="w-2/5">
  <div class="float-right sm:float-none md:float-right ml-20">
    <%= image_tag asset_path('alberto1.jpg') %>
  </div>
  <div class="float-right sm:float-none md:float-right ml-20">
    <%= image_tag asset_path('alberto.jpg') %>
  </div>
  <div class="float-right sm:float-none md:float-right ml-20">
    <%= image_tag asset_path('alberto1.jpg') %>
  </div>
  <div class="float-right sm:float-none md:float-right ml-20">
    <%= image_tag asset_path('alberto.jpg') %>
  </div>
</div>
-->

app/views/pages/home.html.erb
<%= content_for :menu do %>
  ""
<% end %>

<nav>
  <header>
    <div class="pt-3 text-white font-mono pt-12 pl-12">
      <p class="px-6 hover:text-yellow-500 hover:underline text-4xl animate__animated animate__fadeInDown"><%= link_to "BIOGRAFIA", bio_path %></p>
      <p class="px-6 hover:text-yellow-500 hover:underline text-4xl animate__animated animate__fadeInDown"><%= link_to "OBRAS", artworks_path %></p>
      <p class="px-6 hover:text-yellow-500 hover:underline text-4xl animate__animated animate__fadeInDown"><%= link_to "ARTE VIVO", lives_path %></p>
      <p class="px-6 hover:text-yellow-500 hover:underline text-4xl animate__animated animate__fadeInDown"><%= link_to "MUESTRAS", shows_path %></p>
      <p class="px-6 hover:text-yellow-500 hover:underline text-4xl animate__animated animate__fadeInDown"><%= link_to "PUBLICACIONES", shows_path %></p>
      <p class="px-6 hover:text-yellow-500 hover:underline text-4xl animate__animated animate__fadeInDown"><%= link_to "PRENSA", shows_path %></p>
    </div>
  </header>
</nav>

<!-- <div class="flex"> -->

  <!-- <div class="left w-1/2"> -->
  <div>
    <div style="height: 1800px;">
      <div>
        <%= image_tag asset_path('dorso.jpg') %>
      </div>
      <div>
        <%= image_tag asset_path('nun.png') %>
      </div>
      <div>
        <%= image_tag asset_path('fiesta.jpg') %>
      <div>
        <%= image_tag asset_path('nascimiento.jpg') %>
      </div>
      <div>
        <%= image_tag asset_path('sos.jpg') %>
      </div>
      <div>
        <%= image_tag asset_path('grande.jpg') %>
      </div>
      </div>
    </div>
  </div>

<!--
  <div class="right w-1/2">
    <div style="height: 1800px;">
      <div>
        <%= image_tag asset_path('nascimiento.jpg') %>
      </div>
      <div>
        <%= image_tag asset_path('sos.jpg') %>
      </div>
      <div>
        <%= image_tag asset_path('grande.jpg') %>
      </div>
    </div>
  </div> -->

<!-- </div> -->

app/views/phases/index.html.erb
<div class="menu justify-center x-4 w-14 flex-none">
  <div class="bg-gray-300 h-screen px-4 pt-12">
    <% @phases.each do |phase| %>
      <div class="menu_i hover:text-white pt-3 pb-2 uppercase animate__animated animate__fadeInDown"><%= link_to phase.subtitle, phase_path(phase), class:"menu_i_tx hover:text-white" %></div>
    <% end %>
    <!-- <div class="menu_i hover:text-white"><span class="menu_i_tx"><%= link_to "✕", phases_path %></span></div> -->
  </div>
</div>

<div class="flex">

  <div class="left w-1/2">
    <div style="height: 1800px;">
      <div class="uppercase animate__animated animate__fadeInDown">
        <%= image_tag asset_path('nun.png') %>
      </div>
      <div class="uppercase animate__animated animate__fadeInDown">
        <%= image_tag asset_path('dorso.jpg') %>
      </div>
      <div class="uppercase animate__animated animate__fadeInDown">
        <%= image_tag asset_path('fiesta.jpg') %>
      </div>
    </div>
  </div>

  <div class="right w-1/2">
    <div style="height: 1800px;">
      <div class="uppercase animate__animated animate__fadeInDown">
        <%= image_tag asset_path('nascimiento.jpg') %>
      </div>
      <div class="uppercase animate__animated animate__fadeInDown">
        <%= image_tag asset_path('sos.jpg') %>
      </div>
      <div class="uppercase animate__animated animate__fadeInDown">
        <%= image_tag asset_path('grande.jpg') %>
      </div>
    </div>
  </div>

</div>



<!-- <div class="left flex-grow">
  <div class="bg-gray-100 h-screen px-12 py-12">
    <% @phases.each do |phase| %>
    <h1 class="text-4xl hover:text-yellow-500 animate__animated animate__fadeInDown"><%= link_to phase.title, phase_path(phase) %></h1>
    <% end %>
  </div>
</div>
 -->

app/views/phases/show.html.erb
<div class="menu justify-center x-4 w-14 flex-none">
  <div class="bg-gray-300 h-screen px-4 pt-12">
    <% @phases.each do |phase| %>
      <div class="menu_i hover:text-white pt-3 pb-2"><%= link_to phase.subtitle, phase_path(phase), class:"menu_i_tx hover:text-white" %></div>
    <% end %>
    <div class="menu_i hover:text-white"><span class="menu_i_tx"><%= link_to "✕", phases_path %></span></div>
  </div>
</div>

<div class="flex-grow encapsulate pt-12">
  <h1 class=" pb-5 text-4xl"><%= @phase.title %></h1>
  <h2 class=""><%= @phase.subtitle %></h2>
  <h2 class="">De <%= @phase.starting_year %> a <%= @phase.ending_year %></h2>
  <h2 class="pb-5"><%= @phase.about %></h2>
</div>



<!-- <div class="left w-1/6">
  <div style="height: 1800px;">
    <div>
      <%= image_tag asset_path('nun2.png') %>
    </div>
    <div>
      <%= image_tag asset_path('dorso.jpg') %>
    </div>
    <div>
      <%= image_tag asset_path('fiesta.jpg') %>
    </div>
    <div>
      <%= image_tag asset_path('nascimiento.jpg') %>
    </div>
    <div>
      <%= image_tag asset_path('sos.jpg') %>
    </div>
    <div>
      <%= image_tag asset_path('grande.jpg') %>
    </div>
  </div> -->
</div>

app/views/shows/index.html.erb
<div class="menu justify-center x-4 w-14 flex-none">
  <div style="position: fixed;">
    <div class="bg-gray-300 h-screen px-4 pt-12">
      <% @shows.each do |show| %>
        <h1 class="menu_i hover:text-white pt-3 pb-2 uppercase">
          <div class="menu_i_tx over:text-white"><%= show.subtitle%></div>
        </h1>
      <% end %>
    </div>
  </div>
  <!-- <div class="menu_i hover:text-yellow-500"><span class="menu_i_tx"><%= link_to "✕", phases_path %></span></div> -->
</div>


<div class="pt-12 pl-12">
  <h1 class="pb-6 text-yellow-500 text-4xl animate__animated animate__fadeInDown">MUESTRAS</h1>

  <div>
    <% @shows.each do |show| %>
    <div class="py-2">
      <h1 class=""><%= show.year %></h1>
      <h1><%= show.place %>. <%= show.city %>, <%= show.country %></h1>
      <div>
        <img class="float-left pb-2 pr-2" src="/app/assets/images/dorso.jpg">
        <h1><%= show.about %></h1>
      </div>
    </div>
    <% end %>
  </div>

</div>

app/views/shows/show.html.erb
<div class="menu justify-center x-4 w-14 flex-none">
  <div class="bg-gray-300 h-screen px-4 pt-12">
    <% @shows.each do |show| %>
      <h1 class="menu_i hover:text-white pt-3 pb-2 uppercase animate__animated animate__fadeInDown"><%= link_to show.subtitle, show_path(show), class:"menu_i_tx over:text-white" %></h1>
    <% end %>
    <!-- <div class="menu_i hover:text-yellow-500"><span class="menu_i_tx"><%= link_to "✕", phases_path %></span></div> -->
  </div>
</div>

<div>
  <% @shows.each do |show| %>
    <h1 class=""><%= show.year %></h1>
    <h1><%= show.place %></h1>
    <h1><%= show.city %></h1>
    <h1><%= show.country %></h1>
    <h1><%= show.about %></h1>
  <% end %>
</div>













<!--
<div class="menu justify-center x-4 w-14 flex-none">
  <div class="bg-yellow-100 h-screen px-4">
    <div class="menu_i hover:text-yellow-500 pt-7 pb-4"><span class="menu_i_tx">Proxima > </div>
    <div class="menu_i hover:text-yellow-500"><span class="menu_i_tx"> < Anterior</div>
    <div class="menu_i hover:text-yellow-500"><span class="menu_i_tx"><%= link_to "✕", shows_path %></span></div>
  </div>
</div>


<div class="left flex-grow">

  <div class="bg-gray-100 h-screen encapsulate">
      <h1 class="text-4xl uppercase"><%= @show.title %></h1>
      <h1><%= @show.year %></h1>
      <h1><%= @show.place %></h1>
      <h1><%= @show.city %></h1>
      <h1><%= @show.country %></h1>
  </div>

</div>
 -->

app/views/writings/index.html.erb
<div class="menu justify-center x-4 w-14 flex-none">
  <div class="bg-gray-300 h-screen px-4 pt-12">
    <% @writings.each do |writing| %>
    <h1 class="menu_i hover:text-white pt-3 pb-2 uppercase animate__animated animate__fadeInDown"><%= link_to writing.title, writing_path(writing), class:"menu_i_tx over:text-white" %></h1>

<!--       <h1><%= writing.title %></h1>
      <h1><%= writing.year %></h1>
      <h1><%= writing.place %></h1>
      <h1><%= writing.city %></h1>
      <h1><%= writing.country %></h1> -->
      <% end %>
    </div>
    <div class="menu_i hover:text-yellow-500"><span class="menu_i_tx"><%= link_to "✕", phases_path %></span></div>
  </div>

app/views/writings/show.html.erb
<h1>Writings#show</h1>
<p>Find me in app/views/writings/show.html.erb</p>